apiVersion: apps/v1
kind: Deployment 
metadata:
  name: springboot-deployment
  namespace: springboot
spec:
  selector:
    matchLabels:
      app: springboot-app
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot
          image: vigneshv04/springboot-app:VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 8070 

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  namespace: springboot
spec:
  selector:
  name: springboot-app
  type: NodePort 
  ports:
  - port: 8080
    targetPort: 3100
    nodePort: 30008
    protocol: TCP
 
